# -*- coding: utf-8 -*-
"""Salinan dari BPBD_Damage_Information_Extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G6UUq1VI3Pz6RJfAgkSb-7ReajMrpKLZ
"""

import re
import html
import warnings

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

pd.set_option("display.max_columns",None)
pd.set_option("display.max_rows",100)
pd.set_option("display.max_colwidth",200)

# ==========================================================
# ENTITY DICTIONARY
# ==========================================================

ENTITY_DICT = {

    "House":[
        "rumah",
        "rumah warga",
        "rumah penduduk",
        "hunian"
    ],

    "School":[
        "sekolah",
        "sd",
        "smp",
        "sma",
        "smk",
        "madrasah",
        "tk",
        "mi",
        "mts",
        "ma",
        "madrasah ibtidaiyah",
        "paud",
        "pondok"

    ],

    "Health":[
        "rumah sakit",
        "rs",
        "puskesmas",
        "klinik",
        "posyandu",
        "puskesmas pembantu",
        "upt puskesmas",
        "ugd"
    ],

    "Worship":[
        "masjid",
        "mushola",
        "musholla",
        "langgar",
        "gereja",
        "pura",
        "vihara",
        "klenteng",
        "rumah ibadah"
    ],

    "Office":[
        "kantor",
        "perkantoran",
        "balai desa",
        "kantor desa",
        "kantor kecamatan",
        "kantor kelurahan",
        "gedung pkk"
    ],

    "Market":[
        "pasar",
        "pasar desa",
        "pasar raya",
        "pasar darurat",
        "lapak pasar",
        "bangunan pasar",
        "kios pasar",
        "los pasar"
    ],

    "Business":[
        "kios",
        "toko",
        "ruko",
        "warung",
        "bengkel",
        "tempat usaha",
        "pabrik",
        "UMKM",
        "lapak",
        "gerai",
        "gudang"
    ],

    "Bridge":[
        "jembatan",
        "jembatan gantung"
    ],

    "Land":[
        "lahan",
        "sawah",
        "kebun",
        "hutan",
        "tambak",
        "ladang",
        "perkebunan",
        "persawahan"
    ],

    "Dike":[
        "tanggul",
        "plengsengan",
        "talud",
        "tpt",
        "tebing"
    ],

    "Road":[
        "jalan",
        "ruas jalan",
        "akses jalan",
        "badan jalan",
        "bahu jalan",
        "jalan desa",
        "jalan raya",
        "gang",
        "jalan lingkungan"
    ],

    "Drainage":[
        "drainase",
        "gorong",
        "gorong-gorong",
        "saluran",
        "irigasi"
    ],

    "Electric":[
        "listrik",
        "kabel",
        "tiang listrik",
        "pju"
    ],

    "Telecommunication":[
        "telekomunikasi",
        "tower",
        "bts"
    ]

}

# ==========================================================
# CONDITION DICTIONARY
# ==========================================================

CONDITION_DICT={

    "RB":[
        "rusak berat",
        "roboh",
        "ambruk",
        "hancur total",
        "hancur",
        "rata dengan"
    ],

    "RS":[
        "rusak sedang"
    ],

    "RR":[
        "rusak ringan",
        "retak"
    ],

    "Flood":[
        "tergenang",
        "terendam"
    ],

    "Impact":[
        "terdampak"
    ],

    "Burn":[
        "terbakar",
        "kebakaran"
    ],

    "Collapse":[
        "jebol",
        "putus",
        "longsor",
        "ambrol"
    ]
}

# ==========================================================
# UNIT DICTIONARY
# ==========================================================

UNIT_DICT = {

    "COUNT":[

        "unit",

        "rumah",

        "bangunan",

        "buah",

        "batang",

        "kk"

    ],

    "AREA":[

        "ha",

        "hektar"

    ],

    "LENGTH":[

        "meter",

        "m",

        "km"

    ]

}

# ==========================================================
# NEGATIVE PHRASE
# ==========================================================

NEGATIVE_WORDS=[

    "",
    "-",
    "nihil",
    "none",
    "nan",
    "tidak ada",
    "belum ada",
    "masih pendataan",
    "tidak ditemukan",
    "dalam pendataan"

]

# ==========================================================
# HTML CLEANER
# ==========================================================

import html
import re
import pandas as pd

def normalize_html(text):

    if pd.isna(text):
        return ""

    text = str(text)

    text = html.unescape(text)

    # <br> -> newline
    text = re.sub(
        r"<br\s*/?>",
        "\n",
        text,
        flags=re.IGNORECASE
    )

    # </div> -> newline
    text = re.sub(
        r"</div>",
        "\n",
        text,
        flags=re.IGNORECASE
    )

    # hapus tag lain
    text = re.sub(
        r"<[^>]+>",
        " ",
        text
    )

    return text

# ==========================================================
# SYMBOL NORMALIZATION
# ==========================================================

def normalize_symbol(text):

    symbol_map = {

        "•":"\n",

        "➸":"\n",

        "*":"\n",

        "|":"\n",

        ";":"\n"

    }

    for old,new in symbol_map.items():

        text = text.replace(
            old,
            new
        )

    return text

# ==========================================================
# SPACE NORMALIZATION
# ==========================================================

def normalize_space(text):

    text = text.lower()

    text = re.sub(
        r"[ \t]+",
        " ",
        text
    )

    text = re.sub(
        r"\n+",
        "\n",
        text
    )

    return text.strip()

NUMBER_WORDS = {

    "satu":"1",

    "dua":"2",

    "tiga":"3",

    "empat":"4",

    "lima":"5",

    "enam":"6",

    "tujuh":"7",

    "delapan":"8",

    "sembilan":"9",

    "sepuluh":"10"

}

def normalize_number_words(text):

    for word,num in NUMBER_WORDS.items():

        text = re.sub(

            rf"\b{word}\b",

            num,

            text

        )

    return text

# ==========================================================
# MASTER CLEANER
# ==========================================================

def clean_damage(text):

    text = normalize_html(text)

    text = normalize_symbol(text)

    text = normalize_space(text)

    text = normalize_number_words(text)

    return text

# ==========================================================
# SPLIT SENTENCE
# ==========================================================

def split_damage_text(text):

    text = clean_damage(text)

    lines = []

    for line in text.split("\n"):

        line = line.strip()

        if line == "":
            continue

        # hapus bullet di awal baris saja
        line = re.sub(
            r"^[-•*]+\s*",
            "",
            line
        )

        lines.append(line)

    return lines

# ==========================================================
# FEATURE TEMPLATE
# ==========================================================

FEATURE_TEMPLATE = {

    # ==========================
    # HOUSE
    # ==========================

    "House_RB":0,
    "House_RS":0,
    "House_RR":0,
    "House_Flood":0,
    "House_Impact":0,

    # ==========================
    # SCHOOL
    # ==========================

    "School_RB":0,
    "School_RS":0,
    "School_RR":0,

    # ==========================
    # HEALTH
    # ==========================

    "Health_RB":0,
    "Health_RS":0,
    "Health_RR":0,

    # ==========================
    # WORSHIP
    # ==========================

    "Worship_RB":0,
    "Worship_RS":0,
    "Worship_RR":0,

    # ==========================
    # OFFICE
    # ==========================

    "Office_RB":0,
    "Office_RS":0,
    "Office_RR":0,

    # ==========================
    # MARKET
    # ==========================

    "Market_RB":0,
    "Market_RS":0,
    "Market_RR":0,

    # ==========================
    # BUSINESS
    # ==========================

    "Business_RB":0,
    "Business_RS":0,
    "Business_RR":0,

    # ==========================
    # BRIDGE
    # ==========================

    "Bridge_RB":0,
    "Bridge_RS":0,
    "Bridge_RR":0,

    # # ==========================
    # # TREE
    # # ==========================

    # "Tree_Count":0,

    # ==========================
    # LAND
    # ==========================

    "Land_Ha":0,
    "Land_Burn_Ha":0,

    # ==========================
    # ROAD
    # ==========================

    "Road_Length":0,

    # ==========================
    # DIKE
    # ==========================

    "Dike_RB":0,
    "Dike_RS":0,
    "Dike_RR":0,
    "Dike_Length":0,

    # ==========================
    # DRAINAGE
    # ==========================

    "Drainage_Damage":0

}

# ==========================================================
# CREATE EMPTY FEATURE
# ==========================================================

def create_feature():

    return FEATURE_TEMPLATE.copy()

# ==========================================================
# EXPAND FASUM
# ==========================================================

import re

def expand_fasum_entity(line):

    line = line.lower()

    if "fasum" not in line:
        return line

    mapping = {

        "puskesmas": "puskesmas",
        "rumah sakit": "rumah sakit",
        "rsud": "rsud",
        "klinik": "klinik",

        "sd": "sekolah",
        "smp": "sekolah",
        "sma": "sekolah",
        "smk": "sekolah",
        "paud": "sekolah",
        "tk": "sekolah",
        "madrasah": "sekolah",

        "masjid": "masjid",
        "mushola": "mushola",
        "musholla": "musholla",
        "gereja": "gereja",
        "pura": "pura",
        "vihara": "vihara",

        "kantor desa": "kantor desa",
        "balai desa": "balai desa",

        "pasar": "pasar"
    }

    hasil = re.search(r"\((.*?)\)", line)

    if hasil:

        isi = hasil.group(1)

        for key, value in mapping.items():

            if key in isi:

                line = line.replace("fasum", value)

                break

    return line

# ==========================================================
# FIND ENTITY
# ==========================================================

def find_entity(line):

    line = line.lower()

    entity_found = None

    best_position = 999999

    for entity, keywords in ENTITY_DICT.items():

        for keyword in keywords:

            pos = line.find(keyword)

            if pos != -1:

                if pos < best_position:

                    best_position = pos

                    entity_found = entity

    return entity_found

# ==========================================================
# FIND CONDITION
# ==========================================================

def find_condition(line):

    line = line.lower()

    for condition, keywords in CONDITION_DICT.items():

        for keyword in keywords:

            if keyword in line:

                return condition

    return None

import re

def normalize_numeric(text):
    """
    Normalisasi format angka pada kolom Damage.
    """

    if text is None:
        return ""

    text = str(text)

    # hilangkan simbol ±
    text = text.replace("±", "")

    # hilangkan simbol +-
    text = text.replace("+-", "")

    # hilangkan simbol -+
    text = text.replace("-+", "")

    # ubah koma desimal menjadi titik
    text = re.sub(r'(\d),(\d)', r'\1.\2', text)

    # hilangkan pemisah ribuan
    text = re.sub(r'(?<=\d)\.(?=\d{3}\b)', '', text)

    return text

def find_number(line, entity=None):

    line = normalize_numeric(line.lower())

    patterns = [

        r'(\d+(?:\.\d+)?)\s*unit',
        r'(\d+(?:\.\d+)?)\s*rumah',
        r'(\d+(?:\.\d+)?)\s*kk',
        r'(\d+(?:\.\d+)?)\s*ha',
        r'(\d+(?:\.\d+)?)\s*hektar',
        r'(\d+(?:\.\d+)?)\s*meter',
        r'(\d+(?:\.\d+)?)\s*m\b',
        r'(\d+(?:\.\d+)?)\s*km'

    ]

    for pattern in patterns:

        m = re.search(pattern, line)

        if m:

            return float(m.group(1))

    if entity is not None:

        for keyword in ENTITY_DICT.get(entity, []):

            m = re.search(

                rf'(\d+(?:\.\d+)?)\s+{re.escape(keyword)}',

                line

            )

            if m:

                return float(m.group(1))

    m = re.search(

        r'(\d+(?:\.\d+)?)',

        line

    )

    if m:

        return float(m.group(1))

    return 1

#Parser Area
def find_area(line):

    line = normalize_numeric(line.lower())

    m = re.search(

        r"(\d+(?:\.\d+)?)\s*(ha|hektar)",

        line

    )

    if m:

        return float(m.group(1))

    return 0

#Parser Length
import re

def find_length(line):

    line = normalize_numeric(line.lower())

    # =====================================================
    # PRIORITAS 1
    # panjang 120 meter
    # panjang 5 m
    # panjang ± 20 meter
    # =====================================================

    patterns = [

        r'panjang\s*[:=]?\s*±?\s*(\d+(?:\.\d+)?)\s*(km|meter|m)',

        r'sepanjang\s*±?\s*(\d+(?:\.\d+)?)\s*(km|meter|m)',

        r'(\d+(?:\.\d+)?)\s*(km|meter|m)\s*panjang'

    ]

    for pattern in patterns:

        m = re.search(pattern, line)

        if m:

            value = float(m.group(1))

            unit = m.group(2)

            if unit == "km":

                value *= 1000

            return value

    # =====================================================
    # fallback
    # =====================================================

    return 0

#Parser KK
def find_kk(line):

    line = line.lower()

    m = re.search(

        r"(\d+)\s*kk",

        line

    )

    if m:

        return int(m.group(1))

    return 0

# ==========================================================
# DAMAGE FEATURE EXTRACTOR
# ==========================================================

def extract_damage_features(text):

    feature = create_feature()

    lines = split_damage_text(text)

    for line in lines:

        line = expand_fasum_entity(line)
        entity = find_entity(line)

        # if entity is None:
        #     continue

        condition = find_condition(line)

        value = find_number(line, entity)

        # ======================================================
        # HOUSE
        # ======================================================

        if entity == "House":

            if condition == "RB":
                feature["House_RB"] += value

            elif condition == "RS":
                feature["House_RS"] += value

            elif condition == "RR":
                feature["House_RR"] += value

            elif condition == "Flood":

                kk = find_kk(line)

                if kk > 0:
                    feature["House_Flood"] += kk
                else:
                    feature["House_Flood"] += value

            elif condition == "Impact":
                feature["House_Impact"] += value

        # ======================================================
        # SCHOOL
        # ======================================================

        elif entity == "School":

            if condition == "RB":
                feature["School_RB"] += value

            elif condition == "RS":
                feature["School_RS"] += value

            elif condition == "RR":
                feature["School_RR"] += value

        # ======================================================
        # HEALTH
        # ======================================================

        elif entity == "Health":

            if condition == "RB":
                feature["Health_RB"] += value

            elif condition == "RS":
                feature["Health_RS"] += value

            elif condition == "RR":
                feature["Health_RR"] += value

        # ======================================================
        # WORSHIP
        # ======================================================

        elif entity == "Worship":

            if condition == "RB":
                feature["Worship_RB"] += value

            elif condition == "RS":
                feature["Worship_RS"] += value

            elif condition == "RR":
                feature["Worship_RR"] += value

        # ======================================================
        # OFFICE
        # ======================================================

        elif entity == "Office":

            if condition == "RB":
                feature["Office_RB"] += value

            elif condition == "RS":
                feature["Office_RS"] += value

            elif condition == "RR":
                feature["Office_RR"] += value

        # ======================================================
        # MARKET
        # ======================================================

        elif entity == "Market":

            if condition == "RB":
                feature["Market_RB"] += value

            elif condition == "RS":
                feature["Market_RS"] += value

            elif condition == "RR":
                feature["Market_RR"] += value

        # ======================================================
        # BUSINESS
        # ======================================================

        elif entity == "Business":

            if condition == "RB":
                feature["Business_RB"] += value

            elif condition == "RS":
                feature["Business_RS"] += value

            elif condition == "RR":
                feature["Business_RR"] += value

        # ======================================================
        # BRIDGE
        # ======================================================

        elif entity == "Bridge":

            if condition == "RB":
                feature["Bridge_RB"] += value

            elif condition == "RS":
                feature["Bridge_RS"] += value

            elif condition == "RR":
                feature["Bridge_RR"] += value

        # ======================================================
        # LAND
        # ======================================================

        elif entity == "Land":

            area = find_area(line)

            if condition == "Burn":

                feature["Land_Burn_Ha"] += area

            else:

                feature["Land_Ha"] += area

        # ======================================================
        # DIKE
        # ======================================================

        elif entity == "Dike":

            if condition == "RB":
                feature["Dike_RB"] += value

            elif condition == "RS":
                feature["Dike_RS"] += value

            elif condition == "RR":
                feature["Dike_RR"] += value

            length = find_length(line)

            if length > 0:
                feature["Dike_Length"] += length
        # ======================================================
        # ROAD
        # ======================================================

        elif entity == "Road":

            length = find_length(line)

            if length > 0:
                feature["Road_Length"] += length

        # ======================================================
        # DRAINAGE
        # ======================================================

        elif entity == "Drainage":

            feature["Drainage_Damage"] += value

    return feature

__all__ = [
    "clean_damage",
    "extract_damage_features",
]