# -*- coding: utf-8 -*-
"""MODEL_DecisionTree_RandomForest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19JiG_XvaBDoTaos_NN-9pP6-8Ec1Txhs
"""

# IMPORT LIBRARY
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import os
import joblib

from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# ==========================================================
# IMPORT DAMAGE FEATURE ENGINEERING
# ==========================================================

from damage_feature_engineering import (
    clean_damage,
    extract_damage_features
)

# ================
# DATA SELECTION
# ================
print("="*70)
print("MEMBACA DATASET")
print("="*70)
EXCEL_FILE = "kejadian bencana_2020-2025.xlsx"

all_df=[]

for year in range(2020,2026):
    temp=pd.read_excel(
        EXCEL_FILE,
        sheet_name=str(year)
    )

    temp["Year"]=year
    all_df.append(temp)

df=pd.concat(
    all_df,
    ignore_index=True
)

# ==========================================================
# NORMALISASI NAMA KEJADIAN BERDASARKAN JUKLAK BNPB
# ==========================================================

replace_map = {

    # ======================================================
    # BANJIR
    # ======================================================

    "Banjir": "Banjir",
    "Banjir Rob": "Banjir Rob",
    "Banjir Bandang": "Banjir Bandang",
    "Banjir dan Tanah Longsor": "Banjir dan Tanah Longsor",
    "Banjir Drainase & Selokan": "Banjir Drainase & Selokan",
    "Banjir Waduk": "Banjir Waduk",
    "Banjir Genangan": "Banjir Genangan",
    "Tanggul Jebol": "Tanggul Jebol",

    # ======================================================
    # TANAH LONGSOR
    # ======================================================

    "Tanah Longsor": "Tanah Longsor",
    "Gerakan Tanah": "Gerakan Tanah",

    # ======================================================
    # GELOMBANG PASANG DAN ABRASI
    # ======================================================

    "Gelombang Pasang": "Gelombang Pasang",
    "Abrasi": "Abrasi Pantai",

    # ======================================================
    # CUACA EKSTREM
    # ======================================================

    "Angin Puting Beliung": "Puting Beliung",
    "Puting Beliung": "Puting Beliung",
    "Angin Kencang": "Angin Kencang",
    "Angin Topan": "Angin Topan",
    "Hujan Es": "Hujan Es",
    "Siklon Tropis": "Siklon Tropis",
    "Suhu Udara Ekstrem": "Suhu Udara Ekstrem",

    # ======================================================
    # KEKERINGAN
    # ======================================================

    "Kekeringan": "Kekeringan",
    "Kekeringan Meteorologis": "Kekeringan Meteorologis",
    "Kekeringan Hidrologis": "Kekeringan Hidrologis",
    "Kekeringan Pertanian": "Kekeringan Pertanian",

    # ======================================================
    # KEBAKARAN HUTAN DAN LAHAN
    # ======================================================

    "Kebakaran Hutan": "Kebakaran Hutan",
    "Kebakaran Lahan": "Kebakaran Lahan",
    "Kebakaran Lahan Gambut": "Kebakaran Lahan Gambut",

    # ======================================================
    # GEMPA BUMI
    # ======================================================

    "Gempa Bumi": "Gempa Bumi",
    "Gempa Tektonik": "Gempa Tektonik",
    "Gempa Vulkanik": "Gempa Vulkanik",
    "Gempa Runtuhan": "Gempa Runtuhan",

    # ======================================================
    # TSUNAMI
    # ======================================================

    "Tsunami": "Tsunami",
    "Tsunami Seismogenik": "Tsunami Seismogenik",
    "Tsunami Nonseismik": "Tsunami Nonseismik",
    "Tsunami Lokal": "Tsunami Lokal",
    "Tsunami Regional": "Tsunami Regional",
    "Tsunami Jarak": "Tsunami Jarak",
    "Tsunami Meteorologi": "Tsunami Meteorologi",
    "Mikrotsunami": "Mikrotsunami",

    # ======================================================
    # ERUPSI GUNUNG API
    # ======================================================

    "Gunungapi": "Erupsi Gunung Api",
    "Letusan Gunung Api": "Erupsi Gunung Api",
    "Erupsi Gunung Api": "Erupsi Gunung Api",
    "Awan Panas Guguran": "Awan Panas Guguran",
    "Awan Panas": "Awan Panas",
    "Banjir Lahar": "Banjir Lahar",
    "Hujan Abu Vulkanik": "Hujan Abu Vulkanik",
    "Gas Vulkanik Beracun": "Gas Vulkanik Beracun"

}

df["Disaster type"] = (
    df["Disaster type"]
    .fillna("")
    .str.strip()
    .replace(replace_map)
)

allowed_disaster = [

    # BANJIR
    "Banjir",
    "Banjir Rob",
    "Banjir Bandang",
    "Banjir dan Tanah Longsor",
    "Banjir Drainase & Selokan",
    "Banjir Waduk",
    "Banjir Genangan",
    "Tanggul Jebol",

    # TANAH LONGSOR
    "Tanah Longsor",
    "Gerakan Tanah",

    # GELOMBANG PASANG DAN ABRASI
    "Gelombang Pasang",
    "Abrasi Pantai",

    # CUACA EKSTREM
    "Puting Beliung",
    "Angin Kencang",
    "Angin Topan",
    "Hujan Es",
    "Siklon Tropis",
    "Suhu Udara Ekstrem",

    # KEKERINGAN
    "Kekeringan",
    "Kekeringan Meteorologis",
    "Kekeringan Hidrologis",
    "Kekeringan Pertanian",

    # KEBAKARAN HUTAN DAN LAHAN
    "Kebakaran Hutan",
    "Kebakaran Lahan",
    "Kebakaran Lahan Gambut",

    # GEMPA BUMI
    "Gempa Bumi",
    "Gempa Tektonik",
    "Gempa Vulkanik",
    "Gempa Runtuhan",

    # TSUNAMI
    "Tsunami",
    "Tsunami Seismogenik",
    "Tsunami Nonseismik",
    "Tsunami Lokal",
    "Tsunami Regional",
    "Tsunami Jarak",
    "Tsunami Meteorologi",
    "Mikrotsunami",

    # ERUPSI GUNUNG API
    "Erupsi Gunung Api",
    "Awan Panas Guguran",
    "Awan Panas",
    "Banjir Lahar",
    "Hujan Abu Vulkanik",
    "Gas Vulkanik Beracun"

]

df = df[df["Disaster type"].isin(allowed_disaster)].copy()

# ==========================================================
# MEMBUAT KOLOM YEAR DARI EVENTDATE
# ==========================================================

df["Eventdate"] = pd.to_datetime(
    df["Eventdate"],
    format="%d/%m/%Y %H.%M.%S",
    errors="coerce"
)

df["Year"] = df["Eventdate"].dt.year

print(df[["Eventdate", "Year"]].head())

# Memilih atribut yang digunakan sebagai feature dan target
# ==========================================================
# ATTRIBUTE SELECTION
# ==========================================================

df = df[
[
    "Year",
    "Dead",
    "Missing",
    "Serious Wound",
    "Minor Injuries",
    "Damage",
    "Level"
]
].copy()

from google.colab import drive
drive.mount('/content/drive')

# =====================
# DATA PREPROCESSING
# =====================

num_cols=[
    "Dead",
    "Missing",
    "Serious Wound",
    "Minor Injuries"
]

for col in num_cols:

    df[col]=pd.to_numeric(
        df[col],
        errors="coerce"
    )
display(missing.round(2))

# ==========================================================
# CEK MISSING VALUE
# ==========================================================

missing = pd.DataFrame({

    "Missing": df.isna().sum(),

    "Persentase (%)":
    (df.isna().sum()/len(df))*100

})

missing = missing[missing["Missing"]>0]

missing = missing.sort_values(
    "Persentase (%)",
    ascending=False
)

print(missing)

#MISSING VALUE
df[num_cols]=df[num_cols].fillna(0)

#NILAI NEGATIF
for col in num_cols:
    df[col]=df[col].clip(lower=0)

# Membersihkan teks
df["Damage"] = (
    df["Damage"]
    .fillna("")
    .apply(clean_damage)
)

# ==========================================================
# FEATURE ENGINEERING DAMAGE
# ==========================================================
# Ekstraksi fitur
damage_feature_df = (
    df["Damage"]
    .apply(extract_damage_features)
    .apply(pd.Series)
)

#MERGE FEATURE
df = pd.concat(
    [
        df.drop(columns=["Damage"]),
        damage_feature_df
    ],
    axis=1
)

print(f"Jumlah Data : {len(df)}")
print(f"Jumlah Kolom : {len(df.columns)}")

# ==========================================================
# TRAIN TEST SPLIT BERDASARKAN TAHUN
# ==========================================================

train_df = df[df["Year"] <= 2023].copy()

test_df = df[df["Year"] >= 2024].copy()

print("="*70)
print("TRAINING")
print(train_df["Year"].value_counts().sort_index())

print()

print("TESTING")
print(test_df["Year"].value_counts().sort_index())

#DATA TRANSFORMATION
# ==========================================================
# LABEL ENCODING - TARGET
# ==========================================================
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

# Fit hanya pada data training
label_encoder.fit(train_df["Level"])

y_train_main = label_encoder.transform(train_df["Level"])
y_test_main = label_encoder.transform(test_df["Level"])

X_train_main = train_df.drop(columns=["Level", "Year"])
X_test_main = test_df.drop(columns=["Level", "Year"])

#IMPORT SMOTE
from imblearn.over_sampling import SMOTE

# #SMOTE
# def smote_data(X_train,y_train):
#     sm = SMOTE(
#         random_state=42
#     )
#     return sm.fit_resample(
#         X_train,
#         y_train
#     )

# #MODEL UTAMA SETELAH MELAKUKAN SMOTE
# X_train_main_sm,\
# y_train_main_sm = smote_data(
#     X_train_main,
#     y_train_main
# )

from imblearn.over_sampling import SMOTE

# sm = SMOTE(
#     sampling_strategy={
#         1: 3000,   # Sedang
#         2: 3000    # Tinggi
#     },
#     random_state=42
# )

# sm = SMOTE(
#     sampling_strategy={
#         1: 5000,
#         2: 5000
#     },
#     random_state=42
# )

sm = SMOTE(
    sampling_strategy={
        1: 7000,
        2: 7000
    },
    random_state=42
)

X_train_main_sm, y_train_main_sm = sm.fit_resample(
    X_train_main,
    y_train_main
)

from collections import Counter

print("Sebelum SMOTE")
print(Counter(y_train_main))

print()

print("Sesudah SMOTE")
print(Counter(y_train_main_sm))

from sklearn.model_selection import RandomizedSearchCV

pred_dt = dt.predict(X_test_main)

pred_rf = rf.predict(X_test_main)

# #DATA MINING
# #FINAL MODEL DECISION TREE
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(

    criterion="entropy",

    max_depth=None,

    min_samples_leaf=3,

    min_samples_split=2,

    random_state=42

)

dt.fit(
    X_train_main_sm,
    y_train_main_sm
)

pred_dt = dt.predict(X_test_main)

# ==========================================================
# MODEL TERBAIK DECISION TREE
# ==========================================================

dt = dt_search.best_estimator_

pred_dt = dt.predict(X_test_main)

#DECISION RULES
from sklearn.tree import export_text
rules = export_text(
    dt,
    feature_names=list(X_test_main.columns)
)

print(rules)

# DATA MINING
# FINAL MODEL RANDOM FOREST
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(

    n_estimators=500,

    max_depth=None,

    min_samples_leaf=1,

    min_samples_split=10,

    max_features="log2",

    random_state=42,

    n_jobs=-1

)

rf.fit(
    X_train_main_sm,
    y_train_main_sm
)

pred_rf = rf.predict(X_test_main)

# ==========================================================
# MODEL TERBAIK RANDOM FOREST
# ==========================================================

rf = rf_search.best_estimator_

pred_rf = rf.predict(X_test_main)

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

# ==========================================================
# PERBANDINGAN MODEL
# ==========================================================

comparison = pd.DataFrame({

    "Model":[
        "Decision Tree",
        "Random Forest"
    ],

    "Accuracy":[
        accuracy_score(y_test_main,pred_dt),
        accuracy_score(y_test_main,pred_rf)
    ],

    "Precision":[
        precision_score(
            y_test_main,
            pred_dt,
            average="macro"
        ),

        precision_score(
            y_test_main,
            pred_rf,
            average="macro"
        )

    ],

    "Recall":[

        recall_score(
            y_test_main,
            pred_dt,
            average="macro"
        ),

        recall_score(
            y_test_main,
            pred_rf,
            average="macro"
        )

    ],

    "F1-Score":[

        f1_score(
            y_test_main,
            pred_dt,
            average="macro"
        ),

        f1_score(
            y_test_main,
            pred_rf,
            average="macro"
        )

    ]

})

comparison = comparison.round(4)

comparison

# ==========================================================
# FUNCTION EVALUATION
# ==========================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

def evaluate_model(model_name, y_true, y_pred):

    print("\n")
    print("="*70)
    print(f"HASIL EVALUASI {model_name}")
    print("="*70)

    accuracy = accuracy_score(
        y_true,
        y_pred
    )

    precision = precision_score(
        y_true,
        y_pred,
        average="macro"
    )

    recall = recall_score(
        y_true,
        y_pred,
        average="macro"
    )

    f1 = f1_score(
        y_true,
        y_pred,
        average="macro"
    )

    hasil = pd.DataFrame({

        "Metric":[
            "Accuracy",
            "Precision",
            "Recall",
            "F1-Score"
        ],

        "Value":[

            accuracy,
            precision,
            recall,
            f1

        ]

    })

    print("\nMETRIK")
    print(hasil.round(4))
    print("\nCLASSIFICATION REPORT\n")
    print(

        classification_report(

            y_true,
            y_pred,
            target_names=label_encoder.classes_,
            digits=4

        )

    )

    cm = confusion_matrix(
        y_true,
        y_pred
    )

    print("\nCONFUSION MATRIX")
    print(cm)
    return hasil

# hasil_dt = evaluate_model(
#     "Decision Tree",
#     y_test_main,
#     pred_dt
# )

# hasil_rf = evaluate_model(
#     "Random Forest",
#     y_test_main,
#     pred_rf
# )

importance_dt = pd.DataFrame({
    "Feature": X_train_main.columns,
    "Importance": dt.feature_importances_
})

importance_dt = importance_dt.sort_values(
    by="Importance",
    ascending=False
)

print(importance_dt.head(20))

importance_rf = pd.DataFrame({
    "Feature": X_train_main.columns,
    "Importance": rf.feature_importances_
})

importance_rf = importance_rf.sort_values(
    by="Importance",
    ascending=False
)

print(importance_rf.head(20))

# ==========================================================
# PERBANDINGAN MODEL
# ==========================================================

comparison = pd.DataFrame({
    "Model": ["Decision Tree", "Random Forest"],
    "Accuracy": [
        accuracy_score(y_test_main, pred_dt),
        accuracy_score(y_test_main, pred_rf)
    ],
    "Precision": [
        precision_score(y_test_main, pred_dt, average="macro"),
        precision_score(y_test_main, pred_rf, average="macro")
    ],
    "Recall": [
        recall_score(y_test_main, pred_dt, average="macro"),
        recall_score(y_test_main, pred_rf, average="macro")
    ],
    "F1-Score": [
        f1_score(y_test_main, pred_dt, average="macro"),
        f1_score(y_test_main, pred_rf, average="macro")
    ]
})

print("\n")
print("="*70)
print("PERBANDINGAN MODEL")
print("="*70)

print(comparison.round(4))

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

hasil_dt = pd.DataFrame({
    "Year": test_df["Year"].values,
    "Actual": y_test_main,
    "Prediction": pred_dt
})

hasil_rf = pd.DataFrame({
    "Year": test_df["Year"].values,
    "Actual": y_test_main,
    "Prediction": pred_rf
})

hasil_per_tahun_dt = []

for tahun in sorted(hasil_dt["Year"].unique()):

    data = hasil_dt[hasil_dt["Year"] == tahun]

    hasil_per_tahun_dt.append({
        "Tahun": tahun,
        "Accuracy": accuracy_score(data["Actual"], data["Prediction"]),
        "Precision": precision_score(
            data["Actual"],
            data["Prediction"],
            average="weighted",
            zero_division=0
        ),
        "Recall": recall_score(
            data["Actual"],
            data["Prediction"],
            average="weighted",
            zero_division=0
        ),
        "F1-Score": f1_score(
            data["Actual"],
            data["Prediction"],
            average="weighted",
            zero_division=0
        )
    })

hasil_per_tahun_dt = pd.DataFrame(hasil_per_tahun_dt)

print("Decision Tree")
display(hasil_per_tahun_dt.round(4))

hasil_per_tahun_rf = []

for tahun in sorted(hasil_rf["Year"].unique()):

    data = hasil_rf[hasil_rf["Year"] == tahun]

    hasil_per_tahun_rf.append({
        "Tahun": tahun,
        "Accuracy": accuracy_score(data["Actual"], data["Prediction"]),
        "Precision": precision_score(
            data["Actual"],
            data["Prediction"],
            average="weighted",
            zero_division=0
        ),
        "Recall": recall_score(
            data["Actual"],
            data["Prediction"],
            average="weighted",
            zero_division=0
        ),
        "F1-Score": f1_score(
            data["Actual"],
            data["Prediction"],
            average="weighted",
            zero_division=0
        )
    })

hasil_per_tahun_rf = pd.DataFrame(hasil_per_tahun_rf)

print("Random Forest")
display(hasil_per_tahun_rf.round(4))

from sklearn.metrics import confusion_matrix

for tahun in sorted(hasil_dt["Year"].unique()):

    data = hasil_dt[hasil_dt["Year"] == tahun]

    cm = confusion_matrix(
        data["Actual"],
        data["Prediction"]
    )

    print("="*60)
    print(f"Decision Tree - Tahun {tahun}")

    display(pd.DataFrame(
        cm,
        index=["Asli RENDAH","Asli SEDANG","Asli TINGGI"],
        columns=["Pred RENDAH","Pred SEDANG","Pred TINGGI"]
    ))

from sklearn.metrics import confusion_matrix

for tahun in sorted(hasil_rf["Year"].unique()):

    data = hasil_rf[hasil_rf["Year"] == tahun]

    cm = confusion_matrix(
        data["Actual"],
        data["Prediction"]
    )

    print("="*60)
    print(f"Random Forest - Tahun {tahun}")

    display(pd.DataFrame(
        cm,
        index=["Asli RENDAH","Asli SEDANG","Asli TINGGI"],
        columns=["Pred RENDAH","Pred SEDANG","Pred TINGGI"]
    ))

# ==========================================================
# FEATURE ENGINEERING
# ==========================================================

feature_damage = [
    'House_RB',
    'House_RS',
    'House_RR',
    'House_Flood',
    'House_Impact',
    'School_RB',
    'School_RS',
    'School_RR',
    'Health_RB',
    'Health_RS',
    'Health_RR',
    'Worship_RB',
    'Worship_RS',
    'Worship_RR',
    'Office_RB',
    'Office_RS',
    'Office_RR',
    'Market_RB',
    'Market_RS',
    'Market_RR',
    'Business_RB',
    'Business_RS',
    'Business_RR',
    'Bridge_RB',
    'Bridge_RS',
    'Bridge_RR',
    'Land_Ha',
    'Land_Burn_Ha',
    'Road_Length',
    'Dike_RB',
    'Dike_RS',
    'Dike_RR',
    'Dike_Length',
    'Drainage_Damage'
]

summary_feature = pd.DataFrame({
    "Jumlah Data (>0)" : (damage_feature_df[feature_damage] > 0).sum(),
    "Rata-rata" : damage_feature_df[feature_damage].mean(),
    "Maksimum" : damage_feature_df[feature_damage].max()
})

summary_feature = summary_feature.sort_values(
    by="Jumlah Data (>0)",
    ascending=False
)

display(summary_feature)

compare = importance_dt.merge(
    importance_rf,
    on="Feature",
    suffixes=("_DT","_RF")
)

compare = compare.sort_values(
    by="Importance_RF",
    ascending=False
)

display(compare.head(20))

top = compare.head(10)

x = np.arange(len(top))

width = 0.35

plt.figure(figsize=(12,6))

plt.bar(
    x-width/2,
    top["Importance_DT"],
    width,
    label="Decision Tree"
)

plt.bar(
    x+width/2,
    top["Importance_RF"],
    width,
    label="Random Forest"
)

plt.xticks(
    x,
    top["Feature"],
    rotation=45,
    ha="right"
)

plt.ylabel("Importance")

plt.title("Perbandingan Feature Importance")

plt.legend()

plt.tight_layout()

plt.show()

display(hasil_per_tahun_dt)

display(hasil_per_tahun_rf)

print("="*70)
print("MENYIMPAN MODEL")
print("="*70)

os.makedirs(
    "models",
    exist_ok=True
)

os.makedirs(
    "output",
    exist_ok=True
)

importance.to_csv(
    "output/feature_importance.csv",
    index=False
)

comparison.to_csv(
    "output/model_comparison.csv",
    index=False
)

joblib.dump(
    dt,
    "models/decision_tree.joblib"
)

joblib.dump(
    rf,
    "models/random_forest.joblib"
)

joblib.dump(
    label_encoder,
    "models/label_encoder.joblib"
)

joblib.dump(
    list(X_train_main.columns),
    "models/feature_columns.joblib"
)

print()
print("="*70)
print("MODEL BERHASIL DISIMPAN")
print("="*70)

print("Decision Tree   : models/decision_tree.joblib")
print("Random Forest   : models/random_forest.joblib")
print("Label Encoder   : models/label_encoder.joblib")
print("Feature Columns : models/feature_columns.joblib")
print("Label Mapping   : models/label_mapping.joblib")